swagger: "2.0"
info:
  description: Investments Application Swagger file
  version: "1.0.0"
  title: Swagger file
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/investment"

# Routes to application APIs
paths:
  /v1/banks:
    get:
      operationId: "service.APIServer.banks"
      tags:
        - "Banks"
      summary: "A list of bank names"
      description: "Get the list of all banks"
      responses:
        200:
          description: "Successful get banks list operation"
          schema:
            type: "array"

  /v1/banks/{bank}/funds:
    get:
      parameters:
        - name: bank
          in: path
          description: Bank name to get fund list
          type: string
          required: True
      operationId: "service.APIServer.funds"
      tags:
        - "Funds"
      summary: "A list of fund names by bank"
      description: "Get the list of all funds of a particular bank"
      responses:
        200:
          description: "Successful get funds list operation"
          schema:
            type: "array"

  /v1/types:
    get:
      operationId: "service.APIServer.types"
      tags:
        - "Types"
      summary: "A list of investment type names"
      description: "Get the list of all types"
      responses:
        200:
          description: "Successful get types list operation"
          schema:
            type: "array"

  /v1/investments:
    post:
      operationId: "service.APIServer.insertNewInvestment"
      parameters:
        - name: investmentData
          in: body
          schema:
            type: object
            properties:
              bank:
                type: string
              type:
                type: string
              name:
                type: string
              operation:
                type: object
                properties:
                  date:
                    type: string
                  amount:
                    type: number
              balance:
                type: object
                properties:
                  date:
                    type: string
                  amount:
                    type: number
      tags:
        - "Investments"
      summary: "Insert a new investment item"
      description: "Insert a new  investment item"
      responses:
        201:
          description: "New investment successfully created"
          schema:
            type: "array"
    get:
      operationId: "service.APIServer.investments"
      parameters:
        - name: startDate
          in: query
          description: The start date to get balance values
          type: string
          required: False
          default: "_"
        - name: endDate
          in: query
          description: The end date to get balance values
          type: string
          required: False
          default: "_"
        - name: active
          in: query
          description: Indicate when to fetch active only investments
          type: boolean
          required: False
          default: True
      tags:
        - "Investments"
      summary: "A list with the investments"
      description: "Get the list of investments"
      responses:
        200:
          description: "Successful get a list of investments"
          schema:
            type: "array"

  /v1/investments/{investmentId}:
    get:
      operationId: "service.APIServer.investmentByID"
      parameters:
        - name: investmentId
          in: path
          description: Investment ID to get a specific item from the list
          type: string
          required: True
        - name: startDate
          in: query
          description: The start date to get balance values
          type: string
          required: False
          default: "_"
        - name: endDate
          in: query
          description: The end date to get balance values
          type: string
          required: False
          default: "_"
        - name: active
          in: query
          description: Indicate when to fetch active only investments
          type: boolean
          required: False
          default: True
      tags:
        - "Investments"
      summary: "A list with the investments"
      description: "Get the list of investments"
      responses:
        200:
          description: "Successful get a list of investments"
          schema:
            type: "array"
    patch:
      operationId: "service.APIServer.patchInvestment"
      parameters:
        - name: investmentId
          in: path
          description: Investment ID to of the item to be patched
          type: string
          required: True
        - name: investmentData
          in: body
          schema:
            type: object
            properties:
              bank:
                type: string
              type:
                type: string
              name:
                type: string
      tags:
        - "Investments"
      summary: "Patch an investment item"
      description: "Patch an investment item"
      responses:
        200:
          description: "Successful patched the investment item"
          schema:
            type: "array"
